### ISSUE TITLE
pg_paxos won't compile on ubuntu 18.04 with postgresql 10

### ISSUE THREAD

**Issue by pgray** [citusdata/pg_paxos#16]
Attempted running through the setup in the README and the extension won't compile.

Is this project being maintained at all?

**Comment by ROBERT-MCDOWELL** [comment]
same story with postgresql 11.x

src/pg_paxos.c: In function ‘_PG_init’:
src/pg_paxos.c:138:22: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  ProcessUtility_hook = PgPaxosProcessUtility;
                      ^
In file included from /usr/local/pgsql/include/server/nodes/pg_list.h:40:0,
                 from /usr/local/pgsql/include/server/access/tupdesc.h:19,
                 from /usr/local/pgsql/include/server/funcapi.h:21,
                 from src/pg_paxos.c:17:
src/pg_paxos.c: In function ‘PgPaxosPlanner’:
/usr/local/pgsql/include/server/nodes/nodes.h:628:27: error: implicit declaration of function ‘typeof’; did you mean ‘pg_typeof’? [-Werror=implicit-function-declaration]
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                           ^
src/pg_paxos.c:206:23: note: in expansion of macro ‘copyObject’
   Query *paxosQuery = copyObject(query);
                       ^~~~~~~~~~
/usr/local/pgsql/include/server/nodes/nodes.h:628:40: error: expected ‘)’ before ‘copyObjectImpl’
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                                        ^
src/pg_paxos.c:206:23: note: in expansion of macro ‘copyObject’
   Query *paxosQuery = copyObject(query);
                       ^~~~~~~~~~
/usr/local/pgsql/include/server/nodes/nodes.h:628:25: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                         ^
src/pg_paxos.c:206:23: note: in expansion of macro ‘copyObject’
   Query *paxosQuery = copyObject(query);
                       ^~~~~~~~~~
src/pg_paxos.c: In function ‘PgPaxosExecutorStart’:
src/pg_paxos.c:554:3: error: implicit declaration of function ‘PreventTransactionChain’; did you mean ‘PreventInTransactionBlock’? [-Werror=implicit-function-declaration]
   PreventTransactionChain(isTopLevel, "paxos commands");
   ^~~~~~~~~~~~~~~~~~~~~~~
   PreventInTransactionBlock
src/pg_paxos.c:573:42: error: passing argument 1 of ‘pg_analyze_and_rewrite’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   queryTreeList = pg_analyze_and_rewrite(parseTreeNode, paxosQueryString, NULL, 0);
                                          ^~~~~~~~~~~~~
In file included from /usr/local/pgsql/include/server/tcop/utility.h:17:0,
                 from src/pg_paxos.c:48:
/usr/local/pgsql/include/server/tcop/tcopprot.h:51:14: note: expected ‘RawStmt * {aka struct RawStmt *}’ but argument is of type ‘Node * {aka struct Node *}’
 extern List *pg_analyze_and_rewrite(RawStmt *parsetree,
              ^~~~~~~~~~~~~~~~~~~~~~
src/pg_paxos.c:573:19: error: too few arguments to function ‘pg_analyze_and_rewrite’
   queryTreeList = pg_analyze_and_rewrite(parseTreeNode, paxosQueryString, NULL, 0);
                   ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/pgsql/include/server/tcop/utility.h:17:0,
                 from src/pg_paxos.c:48:
/usr/local/pgsql/include/server/tcop/tcopprot.h:51:14: note: declared here
 extern List *pg_analyze_and_rewrite(RawStmt *parsetree,
              ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/pgsql/include/server/nodes/pg_list.h:40:0,
                 from /usr/local/pgsql/include/server/access/tupdesc.h:19,
                 from /usr/local/pgsql/include/server/funcapi.h:21,
                 from src/pg_paxos.c:17:
src/pg_paxos.c: In function ‘PgPaxosProcessUtility’:
/usr/local/pgsql/include/server/nodes/nodes.h:628:40: error: expected ‘)’ before ‘copyObjectImpl’
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                                        ^
src/pg_paxos.c:826:21: note: in expansion of macro ‘copyObject’
    Node *rawQuery = copyObject(copyStatement->query);
                     ^~~~~~~~~~
/usr/local/pgsql/include/server/nodes/nodes.h:628:25: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                         ^
src/pg_paxos.c:826:21: note: in expansion of macro ‘copyObject’
    Node *rawQuery = copyObject(copyStatement->query);
                     ^~~~~~~~~~
src/pg_paxos.c:841:46: error: passing argument 1 of ‘pg_analyze_and_rewrite’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     List *queryList = pg_analyze_and_rewrite(rawQuery, queryString,
                                              ^~~~~~~~
In file included from /usr/local/pgsql/include/server/tcop/utility.h:17:0,
                 from src/pg_paxos.c:48:
/usr/local/pgsql/include/server/tcop/tcopprot.h:51:14: note: expected ‘RawStmt * {aka struct RawStmt *}’ but argument is of type ‘Node * {aka struct Node *}’
 extern List *pg_analyze_and_rewrite(RawStmt *parsetree,
              ^~~~~~~~~~~~~~~~~~~~~~
src/pg_paxos.c:841:23: error: too few arguments to function ‘pg_analyze_and_rewrite’
     List *queryList = pg_analyze_and_rewrite(rawQuery, queryString,
                       ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/pgsql/include/server/tcop/utility.h:17:0,
                 from src/pg_paxos.c:48:
/usr/local/pgsql/include/server/tcop/tcopprot.h:51:14: note: declared here
 extern List *pg_analyze_and_rewrite(RawStmt *parsetree,
              ^~~~~~~~~~~~~~~~~~~~~~
src/pg_paxos.c:864:30: error: passing argument 1 of ‘PreviousProcessUtilityHook’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   PreviousProcessUtilityHook(parsetree, queryString, context,
                              ^~~~~~~~~
src/pg_paxos.c:864:30: note: expected ‘PlannedStmt * {aka struct PlannedStmt *}’ but argument is of type ‘Node * {aka struct Node *}’
src/pg_paxos.c:865:20: error: passing argument 5 of ‘PreviousProcessUtilityHook’ from incompatible pointer type [-Werror=incompatible-pointer-types]
            params, dest, completionTag);
                    ^~~~
src/pg_paxos.c:865:20: note: expected ‘QueryEnvironment * {aka struct QueryEnvironment *}’ but argument is of type ‘DestReceiver * {aka struct _DestReceiver *}’
src/pg_paxos.c:865:26: error: passing argument 6 of ‘PreviousProcessUtilityHook’ from incompatible pointer type [-Werror=incompatible-pointer-types]
            params, dest, completionTag);
                          ^~~~~~~~~~~~~
src/pg_paxos.c:865:26: note: expected ‘DestReceiver * {aka struct _DestReceiver *}’ but argument is of type ‘char *’
src/pg_paxos.c:864:3: error: too few arguments to function ‘PreviousProcessUtilityHook’
   PreviousProcessUtilityHook(parsetree, queryString, context,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/pg_paxos.c:869:27: error: passing argument 1 of ‘standard_ProcessUtility’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   standard_ProcessUtility(parsetree, queryString, context,
                           ^~~~~~~~~
In file included from src/pg_paxos.c:48:0:
/usr/local/pgsql/include/server/tcop/utility.h:40:13: note: expected ‘PlannedStmt * {aka struct PlannedStmt *}’ but argument is of type ‘Node * {aka struct Node *}’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^~~~~~~~~~~~~~~~~~~~~~~
src/pg_paxos.c:870:17: error: passing argument 5 of ‘standard_ProcessUtility’ from incompatible pointer type [-Werror=incompatible-pointer-types]
         params, dest, completionTag);
                 ^~~~
In file included from src/pg_paxos.c:48:0:
/usr/local/pgsql/include/server/tcop/utility.h:40:13: note: expected ‘QueryEnvironment * {aka struct QueryEnvironment *}’ but argument is of type ‘DestReceiver * {aka struct _DestReceiver *}’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^~~~~~~~~~~~~~~~~~~~~~~
src/pg_paxos.c:870:23: error: passing argument 6 of ‘standard_ProcessUtility’ from incompatible pointer type [-Werror=incompatible-pointer-types]
         params, dest, completionTag);
                       ^~~~~~~~~~~~~
In file included from src/pg_paxos.c:48:0:
/usr/local/pgsql/include/server/tcop/utility.h:40:13: note: expected ‘DestReceiver * {aka struct _DestReceiver *}’ but argument is of type ‘char *’
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^~~~~~~~~~~~~~~~~~~~~~~
src/pg_paxos.c:869:3: error: too few arguments to function ‘standard_ProcessUtility’
   standard_ProcessUtility(parsetree, queryString, context,
   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from src/pg_paxos.c:48:0:
/usr/local/pgsql/include/server/tcop/utility.h:40:13: note: declared here
 extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
             ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [/usr/local/pgsql/lib/pgxs/src/makefiles/../../src/Makefile.global:879: src/pg_paxos.o] Error 1
